### ISSUE TITLE
Can A PR Review Checklist be automated with GitHub actions?

### ISSUE THREAD

**Issue by katyhuff** [arfc/arfc.github.io#185]
This repository's issues are reserved for feature requests, and bug reports, and questions.

## I'm submitting a ...
  - [ ] bug report
  - [x] feature request
  - [ ] question

## Expected Behavior
When someone begins to review a PR, a review checklist should pop up. Ideally the new checklist (to be put in the guides by @Dayvis7 withing issue #184).

This is quite distinct from a pr_template, which is possible already within github. 

Here is a relevant discussion by other folks who want this feature. https://github.community/t/pull-request-review-template/912/25

## Actual Behavior
When someone begins to review a PR, a blank comment box pops up.

## How can this issue be closed?
It seems like this could be possible with GitHub actions, and that other solutions might be in development by github. Please investigate the options and determine a path forward.

This issue can be closed with either:
- confirmation that there is no way to do this, or 
- demonstration that this can be done with github actions or with a pr-review-template file of some kind.

**Comment by Dayvis7** [comment]
I don't believe there's a way to do this. According to the community's thread, they're been "working on it" for two years now, and even though there are comments from June 2020 requesting the feature there's been no news of it. I've looked through GitHub actions relating to PR reviews, review comments, and review templates, yet there's nothing that can let you create a pre-filled comment for reviews.
My suggestion is to add a link to the PR template. This link will take you to the PR review template text which you can copy and paste. Maybe when you click the link, a text file opens with the review template. I think that could be an option, but for right now it doesn't appear to be possible to add a template to a PR Review.
Since the GitHub team hasn't announced it's possible and there are no Actions made for it, I say there's no way to do this yet.

**Comment by katyhuff** [comment]
> My suggestion is to add a link to the PR template. This link will take you to the PR review template text which you can copy and paste. 

This seems like a good idea. Go for it.

**Comment by Dayvis7** [comment]
@katyhuff where can I find the file for the template?

**Comment by Dayvis7** [comment]
Nevermind. Please disregard previous statement.
