### ISSUE TITLE
reported issue

### ISSUE THREAD

**Issue by katyhuff** [arfc/arfc.github.io#20]
Reported via email by @skc222 

```
I was working on the website but stuck with this error and trying to figure it out since yesterday:
Liquid Exception: Liquid syntax error (line 37): Variable '{{PyNE}' was not properly terminated with regexp: /\}\}/ in /_layouts/publications.html
jekyll 3.4.3 | Error:  Liquid syntax error (line 37): Variable '{{PyNE}' was not properly terminated with regexp: /\}\}/

First I thought I did some mistake in editing but even if I just clone and run the command 'jekyll serve' still getting the same error.
I know it is not worth asking but still did you come across with this kinda error before?
```

**Comment by katyhuff** [comment]
I'll need to diagnose it. 
- Did you make any changes to the source branch? 
- Are you in the source branch or the master branch? 
- Are you in the repository directory?
- please copy and past the output of the `history` command.

**Comment by skc222** [comment]
- After forking, I just cloned the repo, following are the commands:

1. git clone git@github.com:skc222/arfc.github.io
`Cloning into 'arfc.github.io'...
remote: Counting objects: 2447, done.
remote: Total 2447 (delta 0), reused 0 (delta 0), pack-reused 2447
Receiving objects: 100% (2447/2447), 223.61 MiB | 7.38 MiB/s, done.
Resolving deltas: 100% (1362/1362), done.
Checking connectivity... done.
`
2. cd arfc.github.io
3. git remote add upstream git@github.com:arfc/arfc.github.io
    (This was not working without upstream)
4. git checkout source
`Already on 'source'
Your branch is up-to-date with 'origin/source'.
`
    Then performed some changes in img and _data and committed 
5.  jekyll serve (This gives following error)
`Configuration file: /home/snehal/arfc.github.io/_config.yml
Configuration file: /home/snehal/arfc.github.io/_config.yml
            Source: /home/snehal/arfc.github.io
       Destination: /home/snehal/arfc.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid syntax error (line 37): Variable '{{PyNE}' was not properly terminated with regexp: /\}\}/ in /_layouts/publications.html
jekyll 3.4.3 | Error:  Liquid syntax error (line 37): Variable '{{PyNE}' was not properly terminated with regexp: /\}\}/
`

**Comment by katyhuff** [comment]
Maybe it's your version of Jekyll. I'm using jekyll version 3.01. It looks like your version of jekyll is more up to date. 

This is what I get ( I cloned into 'web' to make sure it was a clean directory):

```
huff@lise:~/repos $ git clone git@github.com:arfc/arfc.github.io web
Cloning into 'web'...
remote: Counting objects: 2447, done.
remote: Total 2447 (delta 0), reused 0 (delta 0), pack-reused 2447
Receiving objects: 100% (2447/2447), 223.61 MiB | 17.59 MiB/s, done.
Resolving deltas: 100% (1362/1362), done.
Checking connectivity... done.

huff@lise:~/repos $ cd web
huff@lise:~/repos/web(source) $ jekyll build
Configuration file: /home/huff/repos/web/_config.yml
            Source: /home/huff/repos/web
       Destination: /home/huff/repos/web/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 1.006 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

I'll update jekyll and see if it fails on my computer as well.

**Comment by katyhuff** [comment]
Nope, not the jekyll version issue. 

```
huff@lise:~/repos $ sudo gem install jekyll
[sudo] password for huff: 
Fetching: jekyll-3.4.3.gem (100%)
Successfully installed jekyll-3.4.3
Parsing documentation for jekyll-3.4.3
Installing ri documentation for jekyll-3.4.3
Done installing documentation for jekyll after 1 seconds
1 gem installed
huff@lise:~/repos $ git clone git@github.com:arfc/arfc.github.io web
Cloning into 'web'...
remote: Counting objects: 2447, done.
remote: Total 2447 (delta 0), reused 0 (delta 0), pack-reused 2447
Receiving objects: 100% (2447/2447), 223.61 MiB | 8.02 MiB/s, done.
Resolving deltas: 100% (1362/1362), done.
Checking connectivity... done.
huff@lise:~/repos $ cd web
huff@lise:~/repos/web(source) $ ls
_bibliography  _data        img         js        manual  _plugins   pres       research
_config.yml    favicon.ico  _includes   _layouts  papers  positions  Rakefile   style.css
css            feed.xml     index.html  LICENSE   people  _posts     README.md
huff@lise:~/repos/web(source) $ jekyll build
Configuration file: /home/huff/repos/web/_config.yml
            Source: /home/huff/repos/web
       Destination: /home/huff/repos/web/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 1.0 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
huff@lise:~/repos/web(source) $ 
```

What is the output of "git status"

**Comment by katyhuff** [comment]
Try : 

```
sudo gem install jekyll-scholar
jekyll build
```

**Comment by skc222** [comment]
Tried everything, still not working on my laptop.
Following are the outputs of commands:
`snehal@dreams:~$ git clone git@github.com:skc222/arfc.github.io web
Cloning into 'web'...
remote: Counting objects: 2447, done.
remote: Total 2447 (delta 0), reused 0 (delta 0), pack-reused 2447
Receiving objects: 100% (2447/2447), 223.61 MiB | 1.72 MiB/s, done.
Resolving deltas: 100% (1362/1362), done.
Checking connectivity... done.
snehal@dreams:~$ cd web
snehal@dreams:~/web$ ls
_bibliography  favicon.ico  index.html  manual    positions  README.md
_config.yml    feed.xml     js          papers    _posts     research
css            img          _layouts    people    pres       style.css
_data          _includes    LICENSE     _plugins  Rakefile
snehal@dreams:~/web$ jekyll build
Configuration file: /home/snehal/web/_config.yml
            Source: /home/snehal/web
       Destination: /home/snehal/web/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid syntax error (line 37): Variable '{{PyNE}' was not properly terminated with regexp: /\}\}/ in /_layouts/publications.html
jekyll 3.4.3 | Error:  Liquid syntax error (line 37): Variable '{{PyNE}' was not properly terminated with regexp: /\}\}/
snehal@dreams:~/web$ git status
On branch source
Your branch is up-to-date with 'origin/source'.
nothing to commit, working directory clean
snehal@dreams:~/web$ sudo gem install jekyll-scholar
[sudo] password for snehal: 
Successfully installed jekyll-scholar-5.9.1
Parsing documentation for jekyll-scholar-5.9.1
Done installing documentation for jekyll-scholar after 0 seconds
1 gem installed
snehal@dreams:~/web$ jekyll build
Configuration file: /home/snehal/web/_config.yml
            Source: /home/snehal/web
       Destination: /home/snehal/web/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid syntax error (line 37): Variable '{{PyNE}' was not properly terminated with regexp: /\}\}/ in /_layouts/publications.html
jekyll 3.4.3 | Error:  Liquid syntax error (line 37): Variable '{{PyNE}' was not properly terminated with regexp: /\}\}/
`

Is it because I am cloning the forked repo? I don't think so but that is the only difference I can see here.

**Comment by skc222** [comment]
No. That is also not the case.

**Comment by katyhuff** [comment]
-  cloning the forked repo is correct. 
- you did not need to do it into "web". I just did that in the example to have a clean repository. You do not need to do that.
- I'm surprised that installing jekyll scholar didn't help. Maybe a clean build is necessary? (that is, try `rm -rf _site && jekyll build`)
- Anyway, I know what error you're running into. It is a bug from last year, so I'm still confused at how a new jekyll-scholar installation is failing. 
  - This is the bug that you're seeing (found by googling): https://github.com/inukshuk/jekyll-scholar/issues/168
  - This is how it has been fixed in a recent version of jekyll scholar https://github.com/inukshuk/jekyll-scholar/pull/167
  - I have now made a change to the _config.yml file in the repository which should fix this whether you have a current jekyll scholar or not. 


Please execute the following commands and let me know how it goes.

```
cd arfc.github.io
git pull upstream source
rm -rf _site
jekyll build
```

**Comment by skc222** [comment]
Yeah, It is working now.
Thank you so much!

**Comment by katyhuff** [comment]
Yay!
